// pages/index.tsx
/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Logo from '../components/logo'
import { Link as LinkType }  from '../hooks-generated'

const Home = ({ links }: { links: LinkType[]}) => {

  if(!links)
    return (
      <div className='flex flex-col items-center justify-center w-full min-h-screen bg-gray-100'>
        <Head>
          <title>Singlelink under construction</title>
          <meta name="description" content="This Singlelink is under construction!" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className='flex flex-col items-center justify-center w-full max-w-md p-8 rounded-xl text-center'>
        <div className='mb-6' style={{width: 44}}><Logo/></div>
          <h1 className='font-semibold text-2xl mb-4'>Under construction</h1>
          <p className=' mb-6 text-gray-600'>This <a href='https://singlelink.co' target="_blank" className='font-semibold text-indigo-600 hover:underline hover:text-indigo-700' rel="noreferrer">Singlelink</a> page is currently under construction. Be sure to check back soon!</p>
          <Link passHref href="/login">
            <button className='px-8 py-4 w-full bg-indigo-600 w-full text-white font-semibold rounded-xl hover:bg-indigo-700'>Log in to my Singlelink dashboard</button>
          </Link>
        </div>
        <div className='text-gray-600 mt-12 text-xs'>Copyright ©{new Date().getFullYear()} Neutron Creative Inc. All rights reserved.</div>

      </div>
    )
  return (
    <>
    <Head>
      <title>{process.env.META_TITLE}</title>
      <meta name="title" content={process.env.META_TITLE} />
      <meta name="description" content={process.env.META_DESC} />

      <meta property="og:type" content="website" />
      <meta property="og:url" content="https://singlelink.co/" />
      <meta property="og:title" content={process.env.META_TITLE} />
      <meta property="og:description" content={process.env.META_DESC} />
      <meta property="og:image" content={process.env.META_IMG} />

      <meta property="twitter:card" content="summary_large_image" />
      <meta property="twitter:url" content="https://singlelink.co/" />
      <meta property="twitter:title" content={process.env.META_TITLE} />
      <meta property="twitter:description" content={process.env.META_DESC} />
      <meta property="twitter:image" content={process.env.META_IMG} />
    </Head>
    <div className='flex flex-col items-center justify-center w-full max-w-md mx-auto py-16 px-4'>
      {[...links].sort((a,b) => {
        if ((a?.position ?? 0) > (b?.position ?? 0)) return 1
        if ((a?.position ?? 0) < (b?.position ?? 0)) return -1
        return 0
      }).map(link => {
        if(link?.type === 'text')
          return (<div className='text-center flex flex-col items-center justify-center mb-4' key={link?.id}>
            <h1 className="text-3xl mb-4 font-semibold">{link?.label}</h1>
            <h2 className='text-xl text-gray-600'>{link?.content}</h2>
          </div>)
        if(link?.type === 'vanilla')
          return (<a href={link.content ?? '#'} className='shadow hover:scale-105 duration-300 ease-in-out flex flex-col w-full text-center px-3 py-5 mb-3 bg-white text-black text-lg font-medium rounded-lg' key={link?.id}>{link?.label}</a>)
        if(link?.type === 'avatar')
          return (<div className='flex items-center justify-center overflow-hidden w-24 h-24 rounded-full mb-6' key={link?.id}>
            <img alt="User" src={link.content ?? '#'} width='100%' height='auto' />
          </div>)
        if(link?.type === 'youtube')
          return (<div key={link.id} className='embed-container rounded-lg'>
            <iframe src={link.content ?? '#'} frameBorder='0' allowFullScreen></iframe>
          </div>)
      })}
      <div className='text-gray-600 mt-auto mt-10 text-center'>Build your free micro-site in seconds with <a href="https://singlelink.co" className='font-medium text-indigo-600 hover:underline hover:text-indigo-700'>Singlelink</a></div>
    </div>
    </>
  )
}

export async function getServerSideProps() {
  if (!process.env.GRAPHQL_URL) throw Error('Singlelink: GraphQL URL not found!')
  const res = await fetch(process.env.GRAPHQL_URL, {
     "headers": {
        "accept": "application/json",
        "content-type": "application/json",
      },
    "body": "{\"operationName\":\"listLinks\",\"variables\":{},\"query\":\"query listLinks {\\n  listLinks {\\n    id\\n    label\\n    content\\n    type\\n    position\\n    __typename\\n  }\\n}\\n\"}",
    "method": "POST"
  })
  const data = await res.json()
  const links: LinkType[] = data.data.listLinks
  return { props: { links } }

}

export default Home

// editor/pages/index.vue
<template>
  <div class="w-screen min-h-screen flex flex-col lg:flex-row text-black">
    <section class="w-full flex flex-col lg:h-screen p-12 items-start justify-center">
      <div class="flex flex-col max-w-lg w-full mx-auto">
        <h1 class="text-5xl font-bold">Login</h1>
        <p class="opacity-70 font-bold text-2xl mb-8">Manage and monitor your Singlelink sites.</p>
        <a href="#"
           class="flex flex-row items-center font-bold justify-center rounded-full w-full px-8 py-4 text-lg border-gray-300 hover:border-gray-600"
           style="border-width:3px;border-style:solid;">
          <img src="/google-icon.png" class="w-5 mr-4" alt="google-icon" @click="attemptGoogleLogin()"/>
          Sign in with Google
        </a>
        <div class="w-full flex flex-row items-center justify-center opacity-60 my-4">
          <div class="line"></div>
          <p class="mx-4 font-bold">Or, sign in with email</p>
          <div class="line"></div>
        </div>
        <div class="input-group flex flex-col w-full mb-4">
          <label>Email address</label>
          <input v-model="email" type="text" placeholder="e.g. jane@singlelink.co"/>
        </div>
        <div class="input-group flex flex-col w-full mb-4">
          <label>Password</label>
          <input v-model="password" type="password" placeholder="Minimum 8 characters"/>
        </div>
        <div class="flex flex-row items-center justify-apart w-full my-4">
          <div class="flex flex-row justify-start items-center" style="width:150px;">
            <input id="remember-me" name="remember-me" type="checkbox" v-model="rememberMe"
                   style="border-radius:3px;width:15px;height:15px;"/>
            <label for="remember-me" class="opacity-50 ml-3 font-bold"
                   style="margin-bottom:0;width:105px;font-size: 14px;">
              <nobr>Remember me?</nobr>
            </label>
          </div>
          <a href="#" class="text-indigo-500 hover:underline ml-auto font-bold">Forgot your password?</a>
        </div>
        <div @click="attemptEmailLogin()" class="button cursor-pointer">Login to your account</div>
        <a href="/create-account"
           class="mx-auto text-center font-bold text-indigo-500 mb-4 text-sm hover:underline font-bold">Don't have an
          account? Get started free</a>
        <a href="https://singlelink.co" target="_blank"
           class="mx-auto font-bold text-center opacity-50 text-sm hover:underline">Learn more about Singlelink</a>
        <span class="mx-auto font-bold text-center opacity-50 text-sm">©{{ new Date().getFullYear() }} Neutron Creative Inc., All rights reserved.</span>
      </div>
    </section>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: 'Index',
  middleware: 'unauthenticated',

  data: () => {
    return {
      email: '',
      password: '',
      error: '',
      rememberMe: false,
      hostname: process.env.HOSTNAME,
      app_name: process.env.APP_NAME,
      icon_url: process.env.ICON_URL,
      organization: process.env.ORGANIZATION,
      free_signup: process.env.FREE_SIGNUP,
      icon_width: process.env.ICON_WIDTH
    };
  },

  head: {
    title: 'Login - ' + process.env.APP_NAME,
    meta: [
      {charset: 'utf-8'},
      {
        name: 'viewport',
        content: 'width=device-width, initial-scale=1, user-scalable=no'
      },
      {
        hid: 'description',
        name: 'description',
        content: 'Login to your ' + process.env.APP_NAME + ' account.'
      },
      {
        hid: 'twitter:description',
        name: 'twitter:description',
        content: 'Login to your ' + process.env.APP_NAME + ' account.'
      },
      {
        hid: 'og:title',
        name: 'og:title',
        content: 'Login - ' + process.env.APP_NAME
      },
      {
        hid: 'twitter:title',
        name: 'twitter:title',
        content: 'Login - ' + process.env.APP_NAME
      },
      {
        hid: 'og:description',
        name: 'og:description',
        content: 'Login to your ' + process.env.APP_NAME + ' account.'
      },
    ],
  },

  methods: {
    async attemptEmailLogin() {
      this.$nuxt.$loading.start();

      if (!this.email) {
        this.error = 'Email address is required to login.';
        this.$nuxt.$loading.finish();
        return;
      }

      if (!this.password) {
        this.error = 'Password is required to login.';
        this.$nuxt.$loading.finish();
        return;
      }

      this.$cookies.set("remember_auth", this.rememberMe);

      try {
        const response = await this.$axios.post('/user/login', {
          email: this.email,
          password: this.password
        });

        this.$store.commit('auth/login', response.data.token);
        this.$nuxt.$loading.finish();
        await this.$router.push('/dashboard');
      } catch (err) {
        console.log('Login failed');
        console.log(err);

        this.error = 'Your email or password is incorrect!';
        await this.$nuxt.$loading.finish();
      }
    },

    async attemptGoogleLogin() {
      this.$cookies.set("remember_auth", this.rememberMe);

      const response = await this.$axios.post('/auth/google/request-login');

      window.location.assign(response.data);
    },

    clearErrors() {
      this.error = '';
    }
  }
});
</script>

<style>
body {
  background: #FEFEFE;
}

.NeutronLogo {
  width: 180px;
}

* {
  outline: none !important;
}

.right {
  background-color: #5353EC;
  background-image: url('/login-lightning.png');
  background-size: 100% 100%;
  background-repeat: no-repeat;
  background-position: top left;
}

.line {
  height: 1px;
  width: auto;
  flex-grow: 1;
  background: rgba(0, 0, 0, .2);
}

label {
  @apply mb-2 text-lg font-bold;
}

.input-group input {
  @apply w-full rounded-full px-8 py-3 text-lg text-gray-800 font-bold outline-none;
  box-shadow: 0 0 0 3px rgba(0, 0, 0, .1);
  transition: .1s ease-in;
}

.input-group input:focus {
  box-shadow: 0 0 0 4.5px rgba(83, 83, 236, .8);
}

.button {
  color: #FFF !important;
}

.button {
  @apply mb-8 w-full font-bold rounded-full px-8 py-4 text-lg text-center;
  background: #5353ec;
  background: linear-gradient(to bottom, #5353ec, #1717ca);
  box-shadow: inset 0 0 0 3px rgba(255, 255, 255, .2), 0 2px 25px rgba(83, 83, 267, .25);
  transition: .1s ease-in;
}

.button:hover {
  transform: scale(1.01);
  box-shadow: inset 0 0 0 4px rgba(255, 255, 255, .4), 0 2px 15px rgba(83, 83, 267, .75);
}

.button:focus {
  transform: scale(1);
  box-shadow: inset 0 0 0 5px rgba(255, 255, 255, .5), 0 2px 20px rgba(83, 83, 267, .95);
}
</style>
